# NOTE: DenseRefexpQuery should only be called after DenseRefexpLoad
#goal definition
string query
float32[] boxes # to be used with perspective correction
int32[] selection_orig_idx
int32[] incorrect_idxs # indexes 
---
#result definition
int32 top_box_idx # original index of top refexp result box
int32[] context_boxes_idxs # original indexes of context objects
bool is_ambiguous
string[] predicted_captions
float32[] probs
--- 
#feedback
