#goal definition
sensor_msgs/Image input # image
string query
int32[] incorrect_idxs # indexes 
---
#result definition
string[] captions # N number of semantic description
float32[] boxes # 4N number of bounding values Eg: (x1, y1, w1, h1 .... xN, yN, wN, hN)
float32[] scores # N number of captioning scores
int32 top_box_idx # original index of top refexp result box
int32[] context_boxes_idxs # original indexes of context objects
---
#feedback

 