# NOTE: RelevancyClustering should only be called after DenseRefexpLoad
#goal definition
string query
int32[] incorrect_idxs # indexes 
---
#result definition
int32[] selection_orig_idx # original idxs of selected context objects
--- 
#feedback

